name: "PR CommitGuard Bot"
description: "PR-focused security scanner that automatically analyzes Pull Requests for leaked secrets and insecure changes."

inputs:
  github-token:
    description: "GitHub token to access API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install deps (if any)
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "${GITHUB_ACTION_PATH}/requirements.txt" ]; then
          pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
        fi

    - name: Install bot package
      shell: bash
      run: |
        pip install "${GITHUB_ACTION_PATH}"

    - name: Run bot script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        OPEN_AI_API_KEY: ${{ env.OPENAI_API_KEY }}
        GH_PAT: ${{ env.GH_PAT }}
      run: |
        commitguard --repo "https://github.com/${{ github.repository }}" --n ${{ github.event.pull_request.commits }}
        
        if [ -f "$GITHUB_ACTION_PATH/suspicious_commits.json" ]; then
          cp "$GITHUB_ACTION_PATH/suspicious_commits.json" "$GITHUB_WORKSPACE/suspicious_commits.json"
        fi

        echo "Workspace: $GITHUB_WORKSPACE"
        ls -la

    - name: Upload CommitGuard report artifact
      uses: actions/upload-artifact@v4
      with:
        name: commitguard-report
        path: |
          suspicious_commits.json
          *.md
        if-no-files-found: warn
