SAMPLE_LINES = [
    'token = "xoxb-1234567890-FAKE-TOKEN"',
    'const GITHUB_TOKEN = "ghp_FAKE1234567890FAKEGITHUBTOKEN"',
    'AWS_ACCESS_KEY_ID=AKIAFAKEEXAMPLEKEY1234',
    'password = "supersecret123456"',
    'DB_PASSWORD=pa$$w0rd12345',
    'api_key: "sk_test_FAKESTRIPEKEY1234567890"',
    'SLACK_BOT_TOKEN=xoxp-FAKE-111222333444555',
    'SECRET_KEY = "s3cr3t_that_is_long_enough_to_match"',
    'const slackToken = "xoxb-111111111111-FAKE"',
    'Authorization: Bearer ya29.A0AfH6SMD_FAKE_OAUTH_TOKEN_ABC123456789',
    'cookie_session = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.FAKEPAYLOAD.SIGNATURE"',
    'conn_str="postgres://user:pass@db:5432/app_db"',
    'requests.get(url, verify=False)',
    'curl -k https://example.com',
    'ENV_VAR=SSL_VERIFY=false',
    '--insecure',
    'const password = "admin:admin"',
    'const secret = "c2VjcmV0c3RyaW5nYmFzZTY0ZmFrZQ=="',
    'PUT /login HTTP/1.1',
    'Authorization: Basic dXNlcjpwYXNzd29yZAo=',
    'docker login -u myuser -p superSecretPassword registry.example.com',
    'export DB_PASS="SuperSecretDBPassword123!"',
    'aws_session_token = "FwoGZXIvYXdzEFAFAKESESSIONTOKENEXAMPLE"',
    'KUBE_SECRET: eyJrZXkiOiJ0b2tlbiJ9',
    '-----BEGIN RSA PRIVATE KEY-----MIICWwIBAAKBgQDAfakebase64dataherewhichissufficientlylong-----END RSA PRIVATE KEY-----',
    'git push https://user:verylongpassword@example.com/repo.git',
    'eval $(echo "cGFzc3dvcmQ=" | base64 --decode)',
    'const token = "gho_FAKE_GITHUB_OTHERTYPE_abcdefghijklmnopqrstuvwxyz"',
]